### ISSUE TITLE
Crashes when I try to access

### ISSUE THREAD

**Issue by rgoggans** [mmckegg/web-audio-school#9]
web-audio-school runs but when I try to access the server it crashes with this output

```
Starting server...
Go to http://localhost:9966
200   12ms       327B  /
200    9ms    12.08KB  /web-audio-api-flowchart.png
200   52ms   407.08KB  /vox.wav
200  127ms     1.45MB  /zara.wav
buffer.js:237
    buf.copy(buffer, pos);
        ^

TypeError: buf.copy is not a function
    at Function.Buffer.concat (buffer.js:237:9)
    at Stream.end (/usr/lib/node_modules/web-audio-school/node_modules/beefy/lib/accumulate-error.js:25:26)
    at _end (/usr/lib/node_modules/web-audio-school/node_modules/through/index.js:61:9)
    at Stream.stream.end (/usr/lib/node_modules/web-audio-school/node_modules/through/index.js:70:5)
    at Stream.onend (stream.js:59:10)
    at emitNone (events.js:72:20)
    at Stream.emit (events.js:166:7)
    at drain (/usr/lib/node_modules/web-audio-school/node_modules/through/index.js:33:23)
    at Stream.stream.queue.stream.push (/usr/lib/node_modules/web-audio-school/node_modules/through/index.js:41:5)
    at Stream.end (/usr/lib/node_modules/web-audio-school/node_modules/through/index.js:17:35)

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! web-audio-school@1.2.0 start: `beefy browser-entry.js:bundle.js --index=resources/index.js --cwd resources -- -t [ ./lib/evalify -f lessons/index.js -f styles/index.js ]`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-audio-school@1.2.0 start script 'beefy browser-entry.js:bundle.js --index=resources/index.js --cwd resources -- -t [ ./lib/evalify -f lessons/index.js -f styles/index.js ]'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the web-audio-school package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     beefy browser-entry.js:bundle.js --index=resources/index.js --cwd resources -- -t [ ./lib/evalify -f lessons/index.js -f styles/index.js ]
npm ERR! You can get their info via:
npm ERR!     npm owner ls web-audio-school
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! path npm-debug.log.c55a190e15e9ba2da10fb6014793ad33
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open

npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.c55a190e15e9ba2da10fb6014793ad33'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open 'npm-debug.log.c55a190e15e9ba2da10fb6014793ad33']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: 'npm-debug.log.c55a190e15e9ba2da10fb6014793ad33' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/lib/node_modules/web-audio-school/npm-debug.log
```

I ran it with sudo and got the npm-debug.log here

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle web-audio-school@1.2.0~prestart: web-audio-school@1.2.0
6 silly lifecycle web-audio-school@1.2.0~prestart: no script for prestart, continuing
7 info lifecycle web-audio-school@1.2.0~start: web-audio-school@1.2.0
8 verbose lifecycle web-audio-school@1.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle web-audio-school@1.2.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/lib/node_modules/web-audio-school/node_modules/.bin:/usr/lib/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle web-audio-school@1.2.0~start: CWD: /usr/lib/node_modules/web-audio-school
11 silly lifecycle web-audio-school@1.2.0~start: Args: [ '-c',
11 silly lifecycle   'beefy browser-entry.js:bundle.js --index=resources/index.js --cwd resources -- -t [ ./lib/evalify -f lessons/index.js -f styles/index.js ]' ]
12 silly lifecycle web-audio-school@1.2.0~start: Returned: code: 1  signal: null
13 info lifecycle web-audio-school@1.2.0~start: Failed to exec start script
14 verbose stack Error: web-audio-school@1.2.0 start: `beefy browser-entry.js:bundle.js --index=resources/index.js --cwd resources -- -t [ ./lib/evalify -f lessons/index.js -f styles/index.js ]`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid web-audio-school@1.2.0
16 verbose cwd /usr/lib/node_modules/web-audio-school
17 error Linux 3.19.0-32-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v5.3.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error web-audio-school@1.2.0 start: `beefy browser-entry.js:bundle.js --index=resources/index.js --cwd resources -- -t [ ./lib/evalify -f lessons/index.js -f styles/index.js ]`
22 error Exit status 1
23 error Failed at the web-audio-school@1.2.0 start script 'beefy browser-entry.js:bundle.js --index=resources/index.js --cwd resources -- -t [ ./lib/evalify -f lessons/index.js -f styles/index.js ]'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the web-audio-school package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     beefy browser-entry.js:bundle.js --index=resources/index.js --cwd resources -- -t [ ./lib/evalify -f lessons/index.js -f styles/index.js ]
23 error You can get their info via:
23 error     npm owner ls web-audio-school
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

thanks for your help

**Comment by ahdinosaur** [comment]
error seems to be coming from `beefy`, related to https://github.com/chrisdickinson/beefy/issues/99.

**Comment by mmckegg** [comment]
I should probably switch to use [budo](https://github.com/mattdesl/budo), but in the meantime @rgoggans, you can use the online version at http://mmckegg.github.io/web-audio-school
